# Generated by Django 5.0.3 on 2024-03-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='map',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.RemoveField(
            model_name='area',
            name='zone',
        ),
        migrations.AddField(
            model_name='area',
            name='zone',
            field=models.ManyToManyField(blank=True, related_name='area', to='guide.zone'),
        ),
    ]
