# Generated by Django 5.0.3 on 2024-03-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_alter_area_map_remove_area_zone_area_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('grade', models.PositiveIntegerField()),
                ('fa', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('area_id', models.PositiveIntegerField(null=True)),
                ('area', models.ManyToManyField(blank=True, related_name='problem', to='guide.area')),
            ],
        ),
    ]
