# Generated by Django 5.0.3 on 2024-03-30 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_problem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='area_id',
            new_name='map_id',
        ),
        migrations.RemoveField(
            model_name='area',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='area',
        ),
        migrations.AddField(
            model_name='area',
            name='zone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area', to='guide.zone'),
        ),
        migrations.AddField(
            model_name='problem',
            name='area',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem', to='guide.area'),
        ),
    ]
