# Generated by Django 5.0.3 on 2024-03-30 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_rename_area_id_problem_map_id_remove_area_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guide.zone'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guide.area'),
        ),
    ]
