# Generated by Django 5.0.3 on 2024-03-31 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0010_rename_ratings_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='user_grade',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(17)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user_rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
