# Generated by Django 5.0.3 on 2024-03-31 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0012_rename_problem_rating_problem_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='problem_name',
            new_name='problem',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user_name',
            new_name='user',
        ),
    ]
