# Generated by Django 5.0.3 on 2024-04-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0013_rename_problem_name_rating_problem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='avgrating',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
