# Generated by Django 5.0.3 on 2024-04-04 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0018_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guide.problem'),
        ),
    ]
